Fixed issue #7.  When checking if a class exists now look for any Throwable instead of just ClassNotFoundException.  Some implementations incorrectly throw a NoClassDefFoundError such as the Sony Ericsson K800i and K850i.